steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/my-image', '.']

  # Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/my-image']

  # Deploy the image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'pgbouncer-docker'
      - '--image'
      - 'europe-west2-docker.pkg.dev/$PROJECT_ID/$REPO_NAME:latest'
      - '--platform'
      - 'managed'
      - '--region'
      - 'europe-west2'
      - '--port'
      - '5432'
options:
  logging: CLOUD_LOGGING_ONLY